#!/usr/bin/python3
def raise_exception_msg(message=""):
    try:
        a - 3
    except NameError:
        print(message)
